version: "3.1"
services:
  backend:
    image: node:latest
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
    restart: always
    command: bash -c "cd /app && npm install && npm start"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    restart: always
  frontend:
    image: node:latest
    ports:
      - "5000:5000"
    volumes:
      - ./front:/app
    restart: always
    command: bash -c "cd /app && npm install && npm start"
